# Generated by Django 5.0.6 on 2024-06-04 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_city_record_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('apartment_number', models.CharField(max_length=10, unique=True)),
                ('cnic_number', models.CharField(max_length=15, null=True, unique=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('numberofpersons', models.CharField(max_length=25, null=True)),
                ('entry_code', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
