# Generated by Django 5.0.6 on 2024-06-04 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('visit_code', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
